version: 2.1

jobs:
  docker-build:
    resource_class: medium
    machine: true
    steps:
      - checkout
      - run:
          name: Build & Test image
          command: |
            make all
workflows:
  ci_build:
    jobs:
      - hold:
          type: approval
      - docker-build:
          requires:
            - hold
