version: 2.1

jobs:
  docker-build:
    resource_class: large
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            make version=test build
      - run:
          name: Test image
          command: |
            make version=test test
workflows:
  ci_build:
    jobs:
      - hold:
          type: approval
      - docker-build:
          requires:
            - hold
